name: Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v1
      - id: readbody
        run: |
          readme_content=`cat ./README.md`
          readme_content="${readme_content//'%'/'%25'}"
          readme_content="${readme_content//$'\n'/'%0A'}"
          readme_content="${readme_content//$'\r'/'%0D'}"
          echo "::set-output name=body::$readme_content"
      - name: JISHIDA PUSH
        uses: ./.
        with:
          key: ${{ secrets.JISHIDA_PUSH_KEY }}
          head: hello
          body: ${{ steps.readbody.outputs.body }}
      - name: JISHIDA PUSH 2
        uses: ./.
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        with:
          key: ${{ secrets.JISHIDA_PUSH_KEY }}
          head: hello
          body: ${{ env.GITHUB_CONTEXT }}
